using System;
using System.Collections.Generic;
using System.Globalization;
using Inkform.Save;
using UnityEngine;
using UnityEngine.UI;

namespace Inkform.UI
{
    /// <summary>
    /// Save menu sheet: three save slots, each showing what its run holds, flanked by left/right
    /// arrows. A tap on a slot continues the run in it (an empty slot starts a new one); a press and
    /// hold on an occupied slot offers to overwrite it, and a second tap confirms.
    ///
    /// Two actions on one button rather than a Delete button per row, because these prefabs are
    /// generated by UIBuilder — adding a widget means regenerating them, and the generated sheet is the
    /// design's. The hold is measured by UiHoldButton, installed onto each slot at runtime here (see
    /// its class docs for how the click that ends a hold gets swallowed).
    ///
    /// Buttons discovered by name: Btn_Slot0..Btn_Slot2, Btn_Left / Btn_Right (arrows, disabled stub).
    /// Each slot's caption is its child Label, the Text UIBuilder.AddButton puts inside every button.
    ///
    /// All captions are ASCII on purpose: the sheet renders in BombSlimeFonts.ttf, which carries Latin
    /// glyphs only — an em dash or a middle dot would come out as a blank box.
    ///
    /// No Back button by design (the sheet's mockup has none): Escape backs out of this sheet, which
    /// UIManager.Update already handles ahead of the pause/main-menu cases.
    /// </summary>
    public class SaveMenuPanel : BasePanel
    {
        // Long enough that no ordinary click reaches it, short enough to find by accident.
        private const float HoldSeconds = 1f;

        // How long an offered overwrite stands before the row goes back to normal. A confirm state that
        // waited forever would be a trap for whoever opens this sheet again later.
        private const float ConfirmSeconds = 3f;

        [SerializeField] private Button[] slotButtons;
        [SerializeField] private Button leftArrow;
        [SerializeField] private Button rightArrow;

        private Text[] slotLabels;
        private UiHoldButton[] slotHolds;

        private int confirmSlot = -1;     // the slot currently offering to be overwritten; -1 = none
        private float confirmSeconds;

        protected override void Awake()
        {
            base.Awake();
            if (slotButtons == null || slotButtons.Length == 0) slotButtons = FindSlotButtons();
            if (leftArrow == null) leftArrow = FindButton("Btn_Left");
            if (rightArrow == null) rightArrow = FindButton("Btn_Right");

            if (slotButtons.Length == 0)
                Debug.LogWarning($"{name}: no Btn_Slot0..2 among the panel's direct children — no way to start a game from here", this);

            slotLabels = new Text[slotButtons.Length];
            slotHolds = new UiHoldButton[slotButtons.Length];

            for (int i = 0; i < slotButtons.Length; i++)
            {
                int slot = i;   // captured per iteration: one shared loop variable would bind every row to the last slot
                Bind(slotButtons[i], $"Btn_Slot{i}", () => OnSlotPressed(slot));

                slotLabels[i] = FindText($"Btn_Slot{i}/Label");

                // Self-installed like UIManager.EnsureGamepadCursor, so the prefab needs no new
                // component and this keeps working after the next UIBuilder run.
                UiHoldButton hold = slotButtons[i].gameObject.AddComponent<UiHoldButton>();
                hold.HoldSeconds = HoldSeconds;
                hold.Held += () => OnSlotHeld(slot);
                slotHolds[i] = hold;
            }

            // Arrows are a placeholder: no save paging exists yet, keep them visible but inert.
            if (leftArrow != null) leftArrow.interactable = false;
            if (rightArrow != null) rightArrow.interactable = false;
        }

        // Rows are painted on open rather than in Awake: a run played and quit since the last time this
        // sheet was shown has to read as changed. Changed covers the rarer case of a slot being written
        // while the sheet is up, which nothing does today but a paging arrow one day might.
        protected override void OnOpen()
        {
            ClearConfirm();
            SaveStore.Changed += Refresh;
            Refresh();
        }

        protected override void OnClose()
        {
            SaveStore.Changed -= Refresh;
            ClearConfirm();
        }

        // The panel outlives its sheet being closed (it is only deactivated), but not the UI Canvas
        // being torn down at play mode end — and a static event holding a destroyed MonoBehaviour is
        // exactly what the buses' ResetStatics exists to prevent.
        void OnDestroy() => SaveStore.Changed -= Refresh;

        void Update()
        {
            if (confirmSlot < 0) return;

            // Unscaled, like every other menu timer (see UiSelectableFx): this sheet can be reached
            // while Time.timeScale is 0.
            confirmSeconds -= Time.unscaledDeltaTime;
            if (confirmSeconds > 0f) return;

            ClearConfirm();
            Refresh();
        }

        // ---- Slot actions ----

        private void OnSlotPressed(int slot)
        {
            // The release that ended a completed hold arrives here as a click. Swallow it — the player
            // is being asked a question, not answering it — and restart the window from the release, so
            // a long hold does not eat the time they have to answer in.
            if (slotHolds[slot] != null && slotHolds[slot].ConsumeSuppressedClick())
            {
                if (confirmSlot == slot) confirmSeconds = ConfirmSeconds;
                return;
            }

            // Standing offer to overwrite this row: this tap is the confirmation.
            if (confirmSlot == slot)
            {
                ClearConfirm();
                UIManager.Instance.StartNewGame(slot);
                return;
            }

            // A tap anywhere else drops an offer made on another row rather than leaving two rows in
            // odd states at once.
            ClearConfirm();

            if (SaveStore.HasSave(slot)) UIManager.Instance.ContinueGame(slot);
            else UIManager.Instance.StartNewGame(slot);
        }

        private void OnSlotHeld(int slot)
        {
            // An empty slot already starts a new game on a plain tap; there is nothing to confirm.
            if (!SaveStore.HasSave(slot)) return;

            confirmSlot = slot;
            confirmSeconds = ConfirmSeconds;
            Refresh();      // the row changes while the button is still down, so letting go reads as safe
        }

        private void ClearConfirm()
        {
            confirmSlot = -1;
            confirmSeconds = 0f;
        }

        // ---- Captions ----

        private void Refresh()
        {
            if (slotLabels == null) return;

            for (int i = 0; i < slotLabels.Length; i++)
            {
                if (slotLabels[i] != null) slotLabels[i].text = CaptionFor(i);
            }
        }

        private string CaptionFor(int slot)
        {
            string head = $"Slot {slot + 1}";

            if (confirmSlot == slot) return $"{head}  -  Overwrite with a new game?\nClick again to confirm";

            SaveData data = SaveStore.Get(slot);
            if (data.IsEmpty) return $"{head}  -  New Game";

            string level = UIManager.Instance != null
                ? UIManager.Instance.LevelDisplayName(data.sceneName)
                : data.sceneName;

            return $"{head}  -  {level}\n{data.sceneName}   {FormatDuration(data.playSeconds)}   {data.deaths} deaths   {FormatSavedAt(data.savedAtUtc)}";
        }

        private static string FormatDuration(float seconds)
        {
            TimeSpan t = TimeSpan.FromSeconds(Mathf.Max(0f, seconds));
            return t.TotalHours >= 1.0
                ? $"{(int)t.TotalHours}:{t.Minutes:00}:{t.Seconds:00}"
                : $"{t.Minutes}:{t.Seconds:00}";
        }

        // Stored as a round-trip UTC string (JsonUtility cannot serialize DateTime); shown in the
        // player's own time zone. An unparseable value is a hand-edited or truncated file — say so
        // quietly rather than throwing on the way to drawing a menu.
        private static string FormatSavedAt(string utcIso)
        {
            if (string.IsNullOrEmpty(utcIso)) return "unknown";

            if (!DateTime.TryParse(utcIso, CultureInfo.InvariantCulture,
                    DateTimeStyles.RoundtripKind, out DateTime saved))
                return "unknown";

            return saved.ToLocalTime().ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture);
        }

        private Button[] FindSlotButtons()
        {
            var found = new List<Button>();
            for (int i = 0; i < SaveStore.SlotCount; i++)
            {
                Button b = FindButton($"Btn_Slot{i}");
                if (b != null) found.Add(b);
            }
            return found.ToArray();
        }
    }
}
