using System;
using UnityEngine;
using UnityEngine.EventSystems;

namespace Inkform.UI
{
    /// <summary>
    /// Press-and-hold on a control that already has a click: after HoldSeconds of an unbroken press it
    /// raises Held, and swallows the click that the release would otherwise produce. That is what lets
    /// one save slot carry two actions — a tap continues the run, a hold offers to overwrite it —
    /// without a second button, which is the whole reason this exists: the UI prefabs are generated by
    /// UIBuilder, and adding a widget means regenerating them.
    ///
    /// Added at runtime by SaveMenuPanel via AddComponent, the same self-installing pattern
    /// UIManager.EnsureGamepadCursor uses, so no prefab changes and nothing to wire per slot.
    ///
    /// Suppression relies on uGUI's dispatch order: the input module sends pointerUp to every handler
    /// on the pressed object and only then sends pointerClick, so OnPointerUp below always runs before
    /// the Button's onClick. The panel asks ConsumeSuppressedClick() first thing in its click handler.
    ///
    /// Timing is unscaled, like everything else in the menu layer (see UiSelectableFx): a hold measured
    /// on scaled time would never complete while the pause menu holds timeScale at 0.
    ///
    /// Gamepad support depends on GamepadCursor sending a real press and a separate release — it used
    /// to fire down/up/click in a single frame, in which case no hold here could ever have started.
    /// Keyboard Enter/Space cannot reach this at all: navigation submit goes through ISubmitHandler,
    /// which fires on the press and has no hold to observe. Keyboard therefore taps only.
    /// </summary>
    public class UiHoldButton : MonoBehaviour, IPointerDownHandler, IPointerUpHandler
    {
        /// <summary>How long the press must last. Set by the installer; 1s is long enough that no
        /// ordinary click reaches it and short enough to discover by accident.</summary>
        public float HoldSeconds { get; set; } = 1f;

        /// <summary>The press passed HoldSeconds. Raised once per press, while the button is still
        /// held — the player sees the row change under their finger, which is the confirmation that
        /// letting go is safe.</summary>
        public event Action Held;

        private bool pressing;
        private float pressSeconds;
        private bool fired;          // Held already raised for this press; do not raise it again
        private bool suppressClick;  // the release that ended a completed hold must not read as a click

        /// <summary>True once, if the click now arriving is the tail of a completed hold. Reading it
        /// clears it.</summary>
        public bool ConsumeSuppressedClick()
        {
            bool value = suppressClick;
            suppressClick = false;
            return value;
        }

        public void OnPointerDown(PointerEventData eventData)
        {
            pressing = true;
            pressSeconds = 0f;
            fired = false;

            // Also clears a suppression nobody collected: releasing a completed hold *outside* the
            // button sends pointerUp but no pointerClick, so the flag would otherwise still be set and
            // would eat the next genuine click instead.
            suppressClick = false;
        }

        public void OnPointerUp(PointerEventData eventData)
        {
            pressing = false;
            if (fired) suppressClick = true;
            fired = false;
        }

        void Update()
        {
            if (!pressing || fired) return;

            pressSeconds += Time.unscaledDeltaTime;
            if (pressSeconds < HoldSeconds) return;

            fired = true;
            Held?.Invoke();
        }

        // Panels hide by SetActive(false) (BasePanel.ApplyState), so a control can be switched off
        // mid-press and never see its OnPointerUp — same hazard UiSelectableFx.OnDisable guards.
        // Leaving suppressClick set here would silently kill the first click after the sheet reopens.
        void OnDisable()
        {
            pressing = false;
            fired = false;
            suppressClick = false;
        }
    }
}
