using Inkform.Item;
using System.Collections.Generic;
using UnityEngine;

namespace Inkform.Interactable.Parts
{
    /// <summary>
    /// Rope hanging: a physical chain (Chain, Verlet rope) from each hanging anchor (HangAnchor child
    /// object) down to this object's attach point — the framework version of the former Bomb's hanging
    /// mode; anchors are collected automatically via the HangAnchor marker
    /// component, no manual references needed.
    ///
    /// Anchor convention: anchors are **child nodes** of the object carrying HangingChain, recognized
    /// by the marker component and collected via GetComponentsInChildren (the child constraint is a
    /// structural guarantee, no runtime validation). At runtime the anchor takes the world position
    /// captured at Attach (pinned to the world, does not move with this object).
    /// Chains can be severed by explosions (Chain subscribes HazardBus.Blast) and by rope-gun shots
    /// (Chain.Active static registry); when all are severed the object is left to its own physics.
    /// Severed chains are unrecoverable — same as the former Bomb's hanging mode.
    /// </summary>
    public class HangingChain : MonoBehaviour, IInteractablePart
    {
        [Header("Hanging")]
        [Tooltip("Attach offset relative to the rigidbody position (e.g. a wall's right edge = half-width,0); zero = center of mass")]
        [SerializeField] private Vector2 attachPoint;
        [Tooltip("Chain tuning pack: segment length/count/iterations/gravity/damping/segment collision/width/sorting")]
        [SerializeField] private Chain.Settings chainSettings = new Chain.Settings();
        [Tooltip("Chain material pack: multiple chains pick materials cyclically, empty slot = default; null = all default")]
        [SerializeField] private ChainMaterialCue materialCue;
        [Tooltip("When enabled, having no HangAnchor children is a configuration error. Disabled means this object is intentionally not hanging.")]
        [SerializeField] private bool requireAnchors;

        [Header("Editor")]
        [Tooltip("Editor only: number of anchors generated by the Generate Hang Anchors menu")]
        [SerializeField] private int anchorCount = 1;
        [Tooltip("Editor only: horizontal spacing between generated anchors")]
        [SerializeField] private Vector2 anchorSpacing = new Vector2(0.6f, 0f);
        [Tooltip("Editor only: how high above the attach point the anchors are generated")]
        [SerializeField] private float anchorHeight = 3f;

        private Interactable root;
        private readonly List<Chain> chains = new List<Chain>();    // chains this object generated; used by CutAllChains

        public void Attach(Interactable root)
        {
            this.root = root;

            Rigidbody2D body = root.GetComponent<Rigidbody2D>();
            if (body == null)
            {
                Debug.LogWarning($"{root.name} has HangingChain but no Rigidbody2D; no chains will be generated", root);
                return;
            }

            // Anchors = HangAnchor marker children, auto-collected: the child constraint is structurally guaranteed
            HangAnchor[] pts = GetComponentsInChildren<HangAnchor>(true);
            if (pts.Length == 0)
            {
                if (requireAnchors)
                    Debug.LogError($"{root.name} requires hanging anchors; right-click and run Generate Hang Anchors", root);
                return;
            }

            chains.Clear();
            // One chain per anchor: anchored to the world (initial world position), following the object
            // however it moves. Chains parent under the anchor (same as the former Bomb): they follow when the
            // anchor is destroyed/moved, keeping the hierarchy clean
            int index = 0;
            foreach (HangAnchor pt in pts)
            {
                GameObject chainGo = new GameObject($"Chain_{pt.name}");
                chainGo.transform.SetParent(pt.transform, false);

                Chain chain = chainGo.AddComponent<Chain>();
                chain.Configure(chainSettings);
                chain.SetMaterial(materialCue != null ? materialCue.PickMaterial(index) : null);   // materials cycle per chain
                chain.Init(body, pt.transform.position, attachPoint);
                chains.Add(chain);
                index++;
            }
        }

        /// <summary>Sever all chains: call when swallowed / released; severed chains are unrecoverable (same hanging semantics as the former Bomb).</summary>
        public void CutAllChains()
        {
            foreach (Chain c in chains) c.CutAll();
        }

        // Pure construction: does not consume contact
        public bool HandleContact(ContactPhase phase, Collider2D other) => false;

        // ---- Editor helpers ----

        // Generates anchorCount anchor children evenly spaced and wired in (old ones cleared first).
        // Note: editor menus may only use the component's own transform — the root cached by Attach is
        // runtime-only
        [ContextMenu("Generate Hang Anchors")]
        private void GenerateHangAnchors()
        {
            ClearHangAnchors();

            int n = Mathf.Max(1, anchorCount);
            for (int i = 0; i < n; i++)
            {
                GameObject go = new GameObject($"HangAnchor_{i + 1}");
                go.transform.SetParent(transform, false);
                go.AddComponent<HangAnchor>();

                // Evenly spaced horizontally around the attach point, raised to the anchor height;
                // drag them in the Scene view afterwards
                float x = (i - (n - 1) * 0.5f) * anchorSpacing.x;
                go.transform.localPosition = (Vector3)attachPoint + new Vector3(x, anchorHeight, 0f);
            }
        }

        [ContextMenu("Clear Hang Anchors")]
        private void ClearHangAnchors()
        {
            HangAnchor[] old = GetComponentsInChildren<HangAnchor>(true);
            foreach (HangAnchor o in old)
            {
                if (Application.isPlaying) Destroy(o.gameObject);
                else DestroyImmediate(o.gameObject);
            }
        }
    }
}
